services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mvc-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-myuser}
      - DB_PASSWORD=${DB_PASSWORD:-mypass}
      - DB_NAME=${DB_NAME:-mydb}
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./:/app:delegated
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mvc-network
    command: /wait-for-it.sh postgres:5432 --timeout=30 -- npm run dev

  postgres:
    image: postgres:15-alpine
    container_name: mvc-database
    environment:
      POSTGRES_DB: ${DB_NAME:-mydb}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypass}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mvc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-myuser} -d ${DB_NAME:-mydb}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mvc-network:
    driver: bridge

volumes:
  postgres-data: